#!/bin/bash

# Fix Render Deployment Script
# This script helps verify and fix the deployment configuration

echo "🔧 Simon Game Deployment Fix Script"
echo "===================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if services are accessible
echo "📋 Checking deployment status..."
echo ""

# Get service URLs from user or try to detect
echo "Please provide your Render service URLs:"
echo ""
read -p "Backend URL (e.g., https://simon-game-backend-XXXX.onrender.com): " BACKEND_URL
read -p "Frontend URL (e.g., https://simon-game-frontend-XXXX.onrender.com): " FRONTEND_URL

if [ -z "$BACKEND_URL" ] || [ -z "$FRONTEND_URL" ]; then
    echo -e "${RED}❌ Both URLs are required${NC}"
    exit 1
fi

echo ""
echo "🧪 Testing backend health endpoint..."
HEALTH_RESPONSE=$(curl -s "$BACKEND_URL/health" 2>/dev/null)

if echo "$HEALTH_RESPONSE" | grep -q "status.*ok"; then
    echo -e "${GREEN}✅ Backend is healthy${NC}"
    echo "   Response: $HEALTH_RESPONSE"
else
    echo -e "${YELLOW}⚠️  Backend health check failed or service is sleeping${NC}"
    echo "   Response: $HEALTH_RESPONSE"
    echo "   (Free tier services sleep after 15 min of inactivity)"
fi

echo ""
echo "📝 Environment Variables to Set in Render:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "FRONTEND SERVICE (simon-game-frontend):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VITE_API_URL = $BACKEND_URL"
echo "  VITE_SOCKET_URL = $BACKEND_URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BACKEND SERVICE (simon-game-backend):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  FRONTEND_URL = $FRONTEND_URL"
echo "  NODE_ENV = production (should already be set)"
echo "  JWT_SECRET = (auto-generated by Render)"
echo "  PORT = 10000 (should already be set)"
echo ""

echo "📋 Steps to fix:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Open 'simon-game-frontend' service"
echo "3. Go to Environment tab"
echo "4. Add/Update:"
echo "   - VITE_API_URL = $BACKEND_URL"
echo "   - VITE_SOCKET_URL = $BACKEND_URL"
echo "5. Go to Manual Deploy tab → Clear build cache & deploy"
echo ""
echo "6. Open 'simon-game-backend' service"
echo "7. Go to Environment tab"
echo "8. Add/Update:"
echo "   - FRONTEND_URL = $FRONTEND_URL"
echo "9. Backend will auto-redeploy"
echo ""
echo -e "${GREEN}✅ After setting these, both services will redeploy automatically${NC}"
echo ""
